from pathlib import Path


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: esperado 1 anchor, encontrado {count}')
    return text.replace(old, new, 1)

# EVOLUCAO_ALFA_SERVICOS.md
path = Path('EVOLUCAO_ALFA_SERVICOS.md')
text = path.read_text(encoding='utf-8')
text = text.replace('> Última atualização: 24/08/2026 às 16:56 (America/Sao_Paulo).', '> Última atualização: 24/08/2026 às 17:11 (America/Sao_Paulo).', 1)

anchor = '''### Produção após a Etapa 0\n\nCommit publicado:\n\n`9c4cfd5d3b619944611012db26cf803c2bee4265`\n\nAlterações desse commit:\n\n- criação de `CONTEXTO_SISTEMA_ALFA.md`;\n- comentários estratégicos `ALFA-DEV` no `index.html`;\n- nenhuma alteração funcional no Firestore;\n- nenhuma alteração no `firebaseConfig`;\n- nenhuma alteração em usuários;\n- nenhuma mudança de schema;\n- deploy de produção confirmado com status de sucesso pela integração Vercel/GitHub.\n'''
insert = anchor + '''\n### Produção após a Etapa 1\n\nCommit funcional publicado:\n\n`5ac984554f046ba68e62da923e7ea72ff3cb6097`\n\nRollback preservado antes da Etapa 1:\n\n`backup/antes-dashboard-inicio-2026-08-24`\n\nAlterações funcionais:\n\n- versão visual `1.7.0`;\n- novo módulo **Início** como primeira tela após o login;\n- indicadores de tarefas vencidas, vencem hoje, próximos 3 dias, alta prioridade e em andamento;\n- listas de atenção e próximos prazos;\n- resumo da equipe para administradores;\n- `Minha fila` para administrador cujo perfil também corresponde a um funcionário;\n- abertura de tarefa diretamente pelo painel reutilizando o modal existente;\n- correção de `todayISO()` para usar `America/Sao_Paulo`;\n- nenhum campo, documento ou coleção nova;\n- nenhuma alteração em `firebaseConfig`, Authentication, Storage ou regras;\n- Preview e deployment de produção da Vercel confirmados com status de sucesso.\n\nValidações realizadas:\n\n- sintaxe JavaScript validada com `node --check`;\n- verificação automática de que o bloco do dashboard não contém `setDoc`, `updateDoc`, `addDoc` ou `deleteDoc`;\n- teste determinístico da virada UTC x horário de São Paulo;\n- revisão do diff do PR;\n- automação visual por navegador não pôde ser executada porque o navegador disponível no ambiente bloqueou páginas locais por política administrativa.\n'''
text = replace_once(text, anchor, insert, 'produção etapa 0')

start = text.index('## ETAPA 1 — Painel Início / Hoje')
end = text.index('## ETAPA 2 — Modo Lista de tarefas')
new_stage1 = '''## ETAPA 1 — Painel Início / Hoje\n\n**Status: ✅ CONCLUÍDA em 24/08/2026**\n\n### Objetivo\n\nTransformar a primeira tela do sistema em uma central de atenção diária, sem adicionar coleção, documento ou campo ao Firestore.\n\n### Implementado\n\n- novo módulo **🏠 Início**;\n- painel aberto automaticamente após login;\n- saudação conforme horário do escritório;\n- tarefas vencidas;\n- tarefas que vencem hoje;\n- tarefas que vencem nos próximos 3 dias;\n- tarefas de prioridade alta;\n- tarefas em andamento;\n- lista de atenção ordenada por urgência;\n- lista de próximos prazos;\n- resumo por responsável para administradores;\n- visão `Minha fila` para administrador associado a funcionário;\n- botão para abrir a tarefa reutilizando o modal existente;\n- botão rápido `+ Novo serviço`;\n- correção segura da data operacional para `America/Sao_Paulo`;\n- comentários `ALFA-DEV` adicionados nos pontos novos;\n- versão visual atualizada para `1.7.0`.\n\n### Segurança confirmada\n\n- nenhuma coleção criada;\n- nenhum campo obrigatório criado;\n- nenhuma tarefa antiga regravada pela abertura do painel;\n- valores de `status` preservados;\n- `firebaseConfig` preservado;\n- Authentication preservado;\n- Storage preservado;\n- Kanban existente preservado;\n- Clientes, Relatórios e Equipe preservados.\n\n### Publicação\n\n- rollback: `backup/antes-dashboard-inicio-2026-08-24`;\n- PR: `#3`;\n- commit funcional: `5ac984554f046ba68e62da923e7ea72ff3cb6097`;\n- Preview Vercel: sucesso;\n- produção Vercel: sucesso.\n\n---\n\n'''
text = text[:start] + new_stage1 + text[end:]
text = text.replace('## ETAPA 2 — Modo Lista de tarefas\n\n**Status: ⚪ PLANEJADA**', '## ETAPA 2 — Modo Lista de tarefas\n\n**Status: 🟡 APROVADA COMO PRÓXIMA ETAPA**', 1)
text = text.replace('| 1 | Painel Início / Hoje | 🟡 Próxima | Muito baixo |', '| 1 | Painel Início / Hoje | ✅ Concluída | Muito baixo |', 1)
text = text.replace('| 2 | Modo Lista | ⚪ Planejada | Baixo |', '| 2 | Modo Lista | 🟡 Próxima | Baixo |', 1)
text = text.replace('**Implementar a ETAPA 1 — Painel Início / Hoje, incluindo correção segura da data local, sem alterar o Firestore.**', '**Implementar a ETAPA 2 — Modo Lista de tarefas, preservando o Kanban e reutilizando os mesmos objetos `tasks` já carregados.**', 1)
path.write_text(text, encoding='utf-8')

# CONTEXTO_SISTEMA_ALFA.md
path = Path('CONTEXTO_SISTEMA_ALFA.md')
text = path.read_text(encoding='utf-8')
text = text.replace('> Última atualização: 24/08/2026.', '> Última atualização: 24/08/2026 às 17:11 (America/Sao_Paulo).', 1)

base = '''- Baseline funcional preservado antes desta documentação:\n  - commit: `9c2dbc5cf622d22426af68f19ed6ef805eebd2fa`;\n  - blob do `index.html`: `13111dd49b22700ceac5ec43f3b3eef625e13a70`;\n  - branch de rollback: `backup/antes-contexto-alfa-2026-08-24`.\n'''
text = replace_once(text, base, base + '''- Release funcional atual após a Etapa 1:\n  - versão visual: `1.7.0`;\n  - commit funcional: `5ac984554f046ba68e62da923e7ea72ff3cb6097`;\n  - rollback anterior à Etapa 1: `backup/antes-dashboard-inicio-2026-08-24`.\n''', 'release atual')

users_anchor = '''### Usuários e perfis\n- `allowedUserEmails`: autorização adicional no frontend.\n- `userProfiles`: nome, perfil e vínculo com funcionário.\n- Alterações futuras em acesso devem ser coordenadas com Authentication e regras, quando expressamente autorizadas.\n\n'''
home_doc = users_anchor + '''### Painel Início / Hoje\n- Tela: `#homeSection`.\n- Navegação: `#viewHomeBtn`.\n- É a primeira view aberta após autenticação bem-sucedida.\n- É uma camada somente de leitura sobre `tasks` e `employees` já carregados.\n- Funções relevantes: `renderHomeDashboard()`, `renderHomeTaskRows()`, `renderHomeTeamSummary()`, `renderHomePersonalQueue()`, `handleHomeAction()`, `isTaskVisibleToCurrentUser()` e `getDashboardEmployeeName()`.\n- Indicadores: vencidas, vencem hoje, próximos 3 dias, alta prioridade e em andamento.\n- Administradores também recebem resumo por responsável.\n- O painel não cria coleção, documento ou campo e não grava no Firestore apenas por ser aberto.\n- Botões do painel reutilizam fluxos existentes, como `openModal()` e a view de tarefas.\n\n### Data operacional\n- Timezone oficial usada para classificar hoje/vencimento: `America/Sao_Paulo`.\n- `todayISO()` não usa mais `toISOString()` diretamente para definir o dia operacional.\n- Helpers novos: `getOfficeDateParts()`, `addDaysISO()`, `calendarDayDiff()`, `getOfficeHour()` e `getOfficeGreeting()`.\n- A mudança afeta apenas cálculos no frontend; datas históricas do Firestore não foram convertidas nem regravadas.\n\n'''
text = replace_once(text, users_anchor, home_doc, 'documentação do painel')

text = text.replace('''- Navegação de módulos:\n  - Tarefas;\n  - Clientes;\n  - Relatórios;\n  - Equipe.\n''', '''- Navegação de módulos:\n  - Início;\n  - Tarefas;\n  - Clientes;\n  - Relatórios;\n  - Equipe.\n''', 1)

text = text.replace('''Funcionalidades efetivamente encontradas no código:\n- login por Firebase Authentication;\n''', '''Funcionalidades efetivamente encontradas no código:\n- login por Firebase Authentication;\n- painel **Início / Hoje** como primeira tela pós-login;\n- indicadores derivados de vencimento, hoje, próximos 3 dias, alta prioridade e andamento;\n- resumo operacional da equipe para administradores;\n- visão `Minha fila` quando o perfil administrativo corresponde a funcionário existente;\n- data operacional calculada em `America/Sao_Paulo`;\n''', 1)

stage0_end = '''**Partes NÃO alteradas**\n- Firestore;\n- coleções/documentos;\n- Firebase Authentication;\n- usuários cadastrados no Firebase;\n- regras do Firestore;\n- regras do Storage;\n- Firebase Storage;\n- `firebaseConfig`;\n- nomes dos campos de tarefas/clientes/equipe.\n\n---\n'''
stage1_doc = stage0_end + '''\n### 24/08/2026 — Etapa 1: Painel Início / Hoje\n**Objetivo:** transformar a primeira tela em uma central operacional diária sem modificar o contrato de dados.\n\n**Solução aplicada**\n- criado `#homeSection` e botão `🏠 Início`;\n- Início passa a abrir automaticamente após login;\n- adicionados KPIs de vencidas, hoje, próximos 3 dias, alta prioridade e em andamento;\n- criadas listas de atenção e próximos prazos;\n- criado resumo por funcionário para administradores;\n- criada `Minha fila` para administrador associado a funcionário;\n- tarefas podem ser abertas pelo painel usando o modal existente;\n- `todayISO()` corrigido para `America/Sao_Paulo`;\n- versão visual atualizada para `1.7.0`;\n- adicionados comentários `ALFA-DEV` na nova área.\n\n**Publicação**\n- rollback: `backup/antes-dashboard-inicio-2026-08-24`;\n- PR: `#3`;\n- commit funcional: `5ac984554f046ba68e62da923e7ea72ff3cb6097`;\n- Preview Vercel: sucesso;\n- produção Vercel: sucesso.\n\n**Validação**\n- sintaxe JavaScript validada;\n- bloco do dashboard verificado como sem chamadas de escrita do Firestore;\n- teste da virada UTC x `America/Sao_Paulo` aprovado;\n- inspeção visual automatizada não foi possível porque o navegador disponível no ambiente bloqueou páginas locais por política administrativa.\n\n**Partes NÃO alteradas**\n- coleções, documentos e campos do Firestore;\n- `firebaseConfig`;\n- Authentication;\n- Storage e suas regras;\n- valores dos status existentes;\n- estrutura base do Kanban, Clientes, Relatórios e Equipe.\n\n---\n'''
text = replace_once(text, stage0_end, stage1_doc, 'changelog etapa1')

old_date = '''### Data local\n- `todayISO()` usa `new Date().toISOString().slice(0, 10)`, portanto calcula a data por UTC.\n- Em horários próximos da virada UTC isso pode divergir do dia local do escritório.\n- Correção recomendada em alteração funcional separada; não foi modificada nesta etapa.\n'''
new_date = '''### Data local\n- Corrigida na Etapa 1.\n- O dia operacional é calculado em `America/Sao_Paulo`.\n- Não voltar a usar `new Date().toISOString().slice(0, 10)` como definição de "hoje" sem avaliar timezone.\n- Datas armazenadas continuam no formato existente; a correção não migrou documentos.\n'''
text = replace_once(text, old_date, new_date, 'data local')

old_next = '''### Prioridade técnica\n1. Confirmar e documentar o projeto/deploy de produção da Vercel conectado a este repositório.\n2. Corrigir `todayISO()` para respeitar a data local do escritório sem alterar datas já gravadas.\n3. Revisar a arquitetura de anexos/Storage em alteração isolada, porque o baseline não contém implementação funcional.\n4. Reduzir progressivamente CSS corretivo duplicado, somente depois de testes visuais de regressão.\n\n### Prioridade de usabilidade — propostas ainda não implementadas neste baseline\n- tela inicial orientada a vencidos, vencimentos de hoje e próximos prazos;\n- modo de lista além do Kanban;\n'''
new_next = '''### Próxima etapa aprovada\n1. Implementar **Modo Lista de tarefas**, preservando o Kanban e reutilizando os mesmos objetos `tasks`.\n\n### Prioridade técnica futura\n1. Revisar a arquitetura de anexos/Storage em alteração isolada, porque o baseline não contém implementação funcional.\n2. Reduzir progressivamente CSS corretivo duplicado, somente depois de testes visuais de regressão.\n\n### Prioridade de usabilidade — ainda não implementadas\n- modo de lista além do Kanban;\n'''
text = replace_once(text, old_next, new_next, 'próximas melhorias')
path.write_text(text, encoding='utf-8')

print('Documentação da Etapa 1 atualizada.')
