from pathlib import Path
import re, subprocess, sys
p=Path('index.html')
expected='aad4083fc0d71e77eefebfa55c2df74fe2c18479'
actual=subprocess.check_output(['git','hash-object','index.html'],text=True).strip()
if actual != expected:
    raise SystemExit(f'baseline inesperado: {actual}')
s=p.read_text(encoding='utf-8')

def rep(old,new,n=1):
    global s
    if old not in s: raise SystemExit('trecho não encontrado: '+old[:80])
    s=s.replace(old,new,n)

def sub(pattern,repl,n=1):
    global s
    s2,c=re.subn(pattern,repl,s,count=n,flags=re.S)
    if c != n: raise SystemExit(f'regex falhou {c}: '+pattern[:80])
    s=s2

s=s.replace('Versão 1.7.0','Versão 1.8.0').replace('versao: "1.7.0"','versao: "1.8.0"')
rep('--blur: blur(22px);','--blur: blur(14px);')
sub(r'  <!-- ALFA-DEV:\nAUTENTICAÇÃO\..*?-->', '''  <!-- ALFA-DEV:\nAUTENTICAÇÃO COMPARTILHADA — v1.8.0.\nO Firebase Authentication permanece como barreira técnica de segurança, porém o sistema usa uma única conta do escritório.\nFuncionários não possuem mais vínculo entre e-mail e tarefas. A seleção operacional acontece pelo card de funcionário.\nNão abrir regras do Firestore para acesso público.\n-->''')
sub(r'      <form id="loginForm">.*?      </div>\n    </div>\n  </section>', '''      <form id="loginForm">\n        <input type="hidden" id="loginEmail" value="alfafiscalto@gmail.com" autocomplete="username">\n        <div class="field">\n          <label for="loginPassword">Senha do escritório</label>\n          <input type="password" id="loginPassword" autocomplete="current-password" required autofocus>\n        </div>\n        <button type="submit" class="btn btn-primary" style="width: 100%; margin-top: 16px;">Entrar no sistema</button>\n      </form>\n\n      <div class="login-helper">\n        <strong>Acesso compartilhado:</strong> a equipe usa uma única conta técnica do Firebase. Depois de entrar, selecione o funcionário pelo card lateral para visualizar ou criar serviços para qualquer pessoa ativa.\n      </div>\n    </div>\n  </section>''')
rep('''      <div class="user-box">\n        <strong>Usuário conectado:</strong><br>\n        <span id="currentUserEmail">-</span>\n      </div>''','''      <div class="user-box">\n        <strong>Acesso do escritório</strong><br>\n        <span id="currentUserEmail">Sessão interna</span>\n      </div>''')
rep('Marque uma ou mais pessoas responsáveis por este serviço. Todos os usuários autorizados podem criar serviço para qualquer funcionário.','Marque uma ou mais pessoas responsáveis. Qualquer pessoa com acesso ao sistema pode criar serviço para qualquer funcionário ativo.')
sub(r'    // ALFA-DEV:\n// AUTORIZAÇÃO NO FRONTEND\..*?    /\*\n      CONFIGURAÇÃO NECESSÁRIA NO FIREBASE', '''    // ALFA-DEV:\n    // ACESSO COMPARTILHADO DO ESCRITÓRIO — v1.8.0.\n    // O Authentication continua protegendo o Firestore, mas não existe mais perfil por funcionário/e-mail.\n    // A conta abaixo é apenas a credencial técnica do escritório; funcionários são escolhidos na interface.\n    // Não trocar por login anônimo e não abrir regras do Firestore para o público.\n    const OFFICE_LOGIN_EMAIL = "alfafiscalto@gmail.com";\n    const SHARED_ACCESS_PROFILE = { name: "equipe", role: "Acesso compartilhado", employee: null };\n\n    function normalizeEmail(email) { return String(email || "").trim().toLowerCase(); }\n    function isAllowedUser(email) { return normalizeEmail(email) === normalizeEmail(OFFICE_LOGIN_EMAIL); }\n    function isAdminUser() { return Boolean(currentUser && isAllowedUser(currentUser.email)); }\n    function currentEmployeeName() { return null; }\n\n    // Os clientes são carregados exclusivamente da coleção "clientes" do Firestore.\n    // Não há lista fixa de clientes neste HTML.\n\n    /*\n      CONFIGURAÇÃO NECESSÁRIA NO FIREBASE''')
rep('''      1) Firebase Console > Authentication > Sign-in method > habilite Email/Password.\n      2) Authentication > Users > Add user:\n         E-mails administrativos: alfacontabilidade2014@gmail.com e alfafiscalto@gmail.com\n         Senha: defina a senha principal informada pelo escritório.\n      3) Firestore Database > Create database.\n      4) Regras recomendadas: liberar somente usuários autorizados listados no sistema.\n         Cole as regras atualizadas informadas junto com este arquivo no Firestore.\n      5) Copie as credenciais do app Web e substitua o objeto firebaseConfig abaixo somente se trocar o projeto Firebase.''','''      1) Firebase Console > Authentication > Sign-in method > habilite Email/Password.\n      2) Authentication > Users: manter a conta técnica alfafiscalto@gmail.com com a senha compartilhada do escritório.\n         Não é necessário criar um usuário Firebase para cada funcionário.\n      3) Firestore Database > manter Cloud Firestore.\n      4) Regras: manter acesso restrito a usuário autenticado/autorizado; NÃO liberar read/write para todos.\n      5) Copie as credenciais do app Web e substitua o objeto firebaseConfig abaixo somente se trocar o projeto Firebase.''')
rep('''    let currentReportRows = [];\n    let selectedEmployee = "todos";\n    let editingTaskId = null;''','''    let currentReportRows = [];\n    let selectedEmployee = "todos";\n    let currentView = "home";\n    let editingTaskId = null;''')
sub(r'    // ALFA-DEV:\n    // VISIBILIDADE COMPARTILHADA ENTRE TAREFAS E PAINEL INÍCIO\..*?    function getHomeDeadlineMeta', '''    // ALFA-DEV:\n    // VISIBILIDADE OPERACIONAL COMPARTILHADA — v1.8.0.\n    // Depois do login técnico do escritório, todos podem consultar todas as tarefas.\n    // O recorte por pessoa acontece SOMENTE pelo seletor selectedEmployee.\n    function isTaskVisibleToCurrentUser() { return Boolean(currentUser && isAllowedUser(currentUser.email)); }\n    function getDashboardEmployeeName() { return null; }\n\n    function getHomeDeadlineMeta''')
sub(r'    function renderHomePersonalQueue\(\) \{.*?\n    \}\n\n    function renderHomeDashboard', '''    function renderHomePersonalQueue() {\n      const panel = document.getElementById("homePersonalPanel");\n      if (!panel) return;\n      panel.style.display = "none";\n      renderHomeTaskRows("homePersonalList", [], "");\n    }\n\n    function renderHomeDashboard''')
rep('const greetingName = currentUserProfile?.name || currentUser?.email || "equipe";','const greetingName = "equipe";')
rep('const subject = isAdminUser() ? "A equipe" : "Você";','const subject = "A equipe";')
sub(r'    function setView\(view\) \{.*?\n    \}\n\n    function monthValue', '''    function setView(view) {\n      currentView = view;\n      document.querySelectorAll("[data-view]").forEach(btn => btn.classList.toggle("active", btn.dataset.view === view));\n      taskSections.forEach(section => { if (section) section.style.display = view === "tasks" ? "" : "none"; });\n      homeSection.classList.toggle("active", view === "home");\n      clientsSection.classList.toggle("active", view === "clients");\n      employeesSection.classList.toggle("active", view === "employees");\n      reportsSection.classList.toggle("active", view === "reports");\n      render();\n    }\n\n    function monthValue''')
sub(r'    function updateEmployeeSelector\(\) \{.*?\n    \}\n\n    function renderEmployeeChoices', '''    function updateEmployeeSelector() {\n      if (!selectedEmployeeLabel || !selectedEmployeeDot || !selectedEmployeeCount || !employeeSelectorBtn) return;\n      const employeeName = selectedEmployee || "todos";\n      selectedEmployeeLabel.textContent = getEmployeeDisplayName(employeeName);\n      selectedEmployeeDot.style.color = getEmployeeColor(employeeName);\n      selectedEmployeeCount.textContent = getEmployeeOpenCount(employeeName);\n      employeeSelectorBtn.disabled = !currentUser;\n      employeeSelectorHint.textContent = currentUser ? "Clique para escolher" : "Entre no sistema";\n    }\n\n    function renderEmployeeChoices''')
sub(r'    function openEmployeeSelectModal\(\) \{.*?\n    \}\n\n    function buildEmployees', '''    function openEmployeeSelectModal() {\n      if (!currentUser) { showToast("Entre no sistema para selecionar um funcionário."); return; }\n      renderEmployeeChoices();\n      employeeSelectModal.classList.add("open");\n      document.body.classList.add("modal-is-open");\n    }\n\n    function closeEmployeeSelectModal() {\n      employeeSelectModal.classList.remove("open");\n      document.body.classList.remove("modal-is-open");\n    }\n\n    function selectEmployee(employeeName, closePicker = false) {\n      selectedEmployee = employeeName || "todos";\n      if (closePicker) closeEmployeeSelectModal();\n      updateEmployeeSelector();\n      const showTasks = () => currentView !== "tasks" ? setView("tasks") : render();\n      if (closePicker) requestAnimationFrame(showTasks); else showTasks();\n    }\n\n    function buildEmployees''')
sub(r'    function buildEmployees\(\) \{.*?\n    \}\n\n    // ALFA-DEV:\n// FILTROS DE TAREFAS\.', '''    function buildEmployees() {\n      employeeInput.innerHTML = "";\n      const reportEmployeeInput = document.getElementById("reportEmployeeInput");\n      const previousReportEmployee = reportEmployeeInput?.value || "todos";\n      if (reportEmployeeInput) reportEmployeeInput.innerHTML = "";\n      employees.forEach(employee => {\n        const inactive = employee.active === false;\n        const label = document.createElement("label");\n        label.className = "employee-check";\n        label.innerHTML = `<input type="checkbox" name="taskEmployees" value="${escapeHTML(employee.name)}" ${inactive ? "disabled" : ""}><span class="employee-check-name"><span class="dot" style="color:${escapeHTML(employee.color)}"></span><span>${escapeHTML(employee.name)}${inactive ? " · inativo" : ""}</span></span>`;\n        employeeInput.appendChild(label);\n      });\n      if (reportEmployeeInput) {\n        reportEmployeeInput.innerHTML = `<option value="todos">Todos</option>`;\n        employees.forEach(employee => { const o=document.createElement("option"); o.value=employee.name; o.textContent=`${employee.name}${employee.active === false ? " (inativo)" : ""}`; reportEmployeeInput.appendChild(o); });\n        reportEmployeeInput.disabled = false;\n        reportEmployeeInput.value = Array.from(reportEmployeeInput.options).some(o => o.value === previousReportEmployee) ? previousReportEmployee : "todos";\n      }\n      if (!selectedEmployee || (selectedEmployee !== "todos" && !getEmployeeByName(selectedEmployee))) selectedEmployee = "todos";\n      updateEmployeeSelector();\n    }\n\n    // ALFA-DEV:\n// FILTROS DE TAREFAS.''')
sub(r'    function getFilteredTasks\(\) \{.*?\n    \}\n\n    function isOverdue', '''    function getFilteredTasks() {\n      const searchTerm = document.getElementById("searchInput").value.trim().toLowerCase();\n      const statusFilter = document.getElementById("statusFilter").value;\n      const priorityFilter = document.getElementById("priorityFilter").value;\n      return tasks.filter(task => {\n        const assigneeText = getTaskAssigneeText(task);\n        const byEmployee = selectedEmployee === "todos" || taskHasEmployee(task, selectedEmployee);\n        const byStatus = statusFilter === "todos" || task.status === statusFilter;\n        const byPriority = priorityFilter === "todas" || task.priority === priorityFilter;\n        const text = [assigneeText, task.clientAlias, task.clientName, task.clientDocument, task.serviceType, task.description, task.observation, task.status, task.priority].filter(Boolean).join(" ").toLowerCase();\n        return byEmployee && byStatus && byPriority && (!searchTerm || text.includes(searchTerm));\n      });\n    }\n\n    function isOverdue''')
rep('''      updateEmployeeSelector();\n      if (employeeSelectModal?.classList.contains("open")) renderEmployeeChoices();\n    }''','''      updateEmployeeSelector();\n    }''')
sub(r'    function render\(\) \{.*?\n    \}\n\n    function openModal', '''    function renderTaskView() {\n      if (selectedEmployee === "todos") document.documentElement.style.setProperty("--red", "#e50914");\n      renderHeader();\n      const filtered = getFilteredTasks();\n      renderStats(filtered);\n      renderColumn("listPendente", filtered.filter(task => task.status === "pendente"));\n      renderColumn("listAndamento", filtered.filter(task => task.status === "andamento"));\n      renderColumn("listConcluido", filtered.filter(task => task.status === "concluido"));\n    }\n\n    function render() {\n      updateEmployeeSelector();\n      if (currentView === "tasks") return renderTaskView();\n      if (currentView === "home") return renderHomeDashboard();\n      if (currentView === "clients") return renderClients();\n      if (currentView === "employees") return renderEmployeesManagement();\n      if (currentView === "reports") return generateReport();\n    }\n\n    function openModal''')
sub(r'      const defaultEmployee = currentUserProfile\?\.employee.*?\n\n      setSelectedTaskEmployees\(selectedNames\);', '''      const defaultEmployee = getActiveEmployees()[0]?.name || employees[0]?.name || "";\n      let selectedNames = [];\n      if (task) selectedNames = getTaskAssignees(task);\n      else if (selectedEmployee && selectedEmployee !== "todos" && getEmployeeByName(selectedEmployee)?.active !== false) selectedNames = [selectedEmployee];\n      else selectedNames = [defaultEmployee];\n\n      setSelectedTaskEmployees(selectedNames);''')
sub(r'    // ALFA-DEV:\n// LOGIN\..*?\n    \}\n\n    async function handleLogout', '''    // ALFA-DEV:\n    // LOGIN COMPARTILHADO — v1.8.0. A interface pede só a senha; o e-mail técnico fica fixo.\n    async function handleLogin(event) {\n      event.preventDefault();\n      if (!firebaseReady) { showToast("Configure o Firebase antes de fazer login."); return; }\n      try { await signInWithEmailAndPassword(auth, OFFICE_LOGIN_EMAIL, document.getElementById("loginPassword").value); }\n      catch (error) { console.error(error); showToast("Senha não autorizada. Confira a senha da conta do escritório no Firebase Authentication."); }\n    }\n\n    async function handleLogout''')
sub(r'    function showApp\(user\) \{.*?\n    \}\n\n    function showLogin', '''    function showApp(user) {\n      currentUser = user;\n      currentUserProfile = { ...SHARED_ACCESS_PROFILE };\n      currentUserEmail.innerHTML = `Alfa Contabilidade<br><small>Acesso compartilhado do escritório</small>`;\n      selectedEmployee = "todos";\n      buildEmployees();\n      ["allTasksBtn","exportBackupBtn","importBackupBtn"].forEach(id => document.getElementById(id).style.display = "inline-flex");\n      document.getElementById("viewEmployeesBtn").style.display = "flex";\n      loginScreen.style.display = "none";\n      appShell.classList.add("visible");\n      setConnection("online", "Conectado ao Firebase");\n      setView("home");\n      listenEmployees(); listenTasks(); listenClients(); remindAdminBackup();\n    }\n\n    function showLogin''')
rep('      currentUserEmail.textContent = "-";','      currentUserEmail.textContent = "Sessão interna";')
s=s.replace('        renderEmployeesManagement();\n        render();','        render();')
rep('''        clients = getMergedClients(firebaseClients);\n        renderClients();\n        buildClientDatalist();''','''        clients = getMergedClients(firebaseClients);\n        buildClientDatalist();\n        if (currentView === "clients") renderClients();''')
rep('''        clients = getMergedClients([]);\n        renderClients();''','''        clients = getMergedClients([]);\n        if (currentView === "clients") renderClients();''')
rep('showToast("Enviamos um link de redefinição de senha para seu e-mail.");','showToast("Enviamos um link de redefinição para o e-mail da conta compartilhada do escritório.");')
rep('>Alterar senha</button>','>Alterar senha do escritório</button>')
rep('''        onAuthStateChanged(auth, (user) => {\n          if (user && isAllowedUser(user.email)) {\n            showApp(user);\n          } else {\n            if (user && !isAllowedUser(user.email)) signOut(auth);\n            showLogin();\n          }\n        });''','''        onAuthStateChanged(auth, (user) => {\n          if (user && isAllowedUser(user.email)) showApp(user);\n          else { if (user && !isAllowedUser(user.email)) signOut(auth); showLogin(); }\n        });''')
rep('// Filtro local sobre dados já carregados: usuário, funcionário, status, prioridade e busca textual.\n// Alterações devem preservar a restrição de visualização aplicada aos usuários não administradores.','// Filtro local sobre dados já carregados: funcionário, status, prioridade e busca textual.\n// v1.8.0: não há mais restrição por e-mail de funcionário; todos usam a conta compartilhada.')
marker='''    /* =========================================================\n       PAINEL INÍCIO / HOJE — v1.7.0'''
perf='''    /* ALFA-DEV PERFORMANCE v1.8.0: seletor sem blur para reduzir repaint/INP. */\n    #employeeSelectModal .modal-card { background: rgba(20,20,31,.985); backdrop-filter:none; -webkit-backdrop-filter:none; box-shadow:0 18px 54px rgba(0,0,0,.42); contain:content; }\n    #employeeSelectModal .modal-header { background: rgba(20,20,31,.99); backdrop-filter:none; -webkit-backdrop-filter:none; }\n\n'''
rep(marker,perf+marker.replace('v1.7.0','v1.8.0'))
s=s.replace('PAINEL INÍCIO / HOJE — v1.7.0.','PAINEL INÍCIO / HOJE — v1.8.0.')

p.write_text(s,encoding='utf-8')
newhash=subprocess.check_output(['git','hash-object','index.html'],text=True).strip()
print('new hash',newhash)
